version: '3'
services:
    php:
        build:
            context: ./docker
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - db
        ports:
            - 80:80
        volumes:
            - './public/:/app'
  
    db:
        image: mariadb
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: blog
            MYSQL_USER: alex
            MYSQL_PASSWORD: monFabuleuxMotDePasse
            MYSQL_ROOT_PASSWORD: dqK_sd7GDqs5ยง6@Dsdq#nM)k7
        volumes:
            - ./docker/database/:/docker-entrypoint-initdb.d
            - ./docker/database/:/var/lib/mysql
    adminer:
        image: 'adminer:latest'
        ports:
            - '8081:8080'
    
